runtime: nodejs20

automatic_scaling:
  target_cpu_utilization: 0.8
  max_instances: 2 

handlers:
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto

env_variables:
  NEXT_PUBLIC_KEYSTATIC_GITHUB_APP_SLUG: akualis-keystatic